apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-rest
  template:
    metadata:
      labels:
        app: weather-rest
    spec:
      containers:
      - name: weather-rest
        image: $REGISTRY-docker.pkg.dev/$PROJECT_ID/sima/weather:$IMAGE_TAG
        imagePullPolicy: Always
        args: ["start-gunicorn-server", "--workers", "4"]
        ports:
        - name: rest
          containerPort: 5000
        envFrom:
          - secretRef:
              name: weather-secret
          - configMapRef:
              name: weather-conf
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
      - name: weather-kafka
        image: $REGISTRY-docker.pkg.dev/$PROJECT_ID/sima/weather:$IMAGE_TAG
        imagePullPolicy: Always
        args: ["start-kafka-consumer"]
        envFrom:
          - secretRef:
              name: weather-secret
          - configMapRef:
              name: weather-conf
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"

      imagePullSecrets:
          - name: regcred
